name: my_deep_link_sdk
description: A Flutter package for deep linking without Firebase.
version: 1.0.0
repository: https://github.com/kishanMoontechnolabs/my_deep_link_sdk
homepage: https://github.com/kishanMoontechnolabs/my_deep_link_sdk
license: MIT

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.4.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.my_deep_link_sdk
        pluginClass: MyDeepLinkSdkPlugin
      ios:
        pluginClass: MyDeepLinkSdkPlugin
